name: Build and deploy Node.js app to Azure Web App - azureactions1

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest 

    steps:
      - uses: actions/checkout@v3

      - name: Set upNode.js 
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'  # Or the version suitable for your app

      - name: Install dependencies
        run: npm install 

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: node-app
          path: . 

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write 

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: node-app

      - name: Login to Azure
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_BD5752943DD84D1EB54BBD610049E8EF }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_B6D2E5F5464A4FB9A8EEA784FC75A024 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_51376753E8BB4AB6BB1C55B7F03E426D }}

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v2
        id: deploy-to-webapp
        with:
          app-name: 'azureactions1'
          slot-name: 'Production'
          package: .

